name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show runner IP
        run: curl -s https://ifconfig.me

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 91.186.217.66
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          debug: true
          script: |
            cd /root/projects/analitics_manager
            git fetch origin main
            git reset --hard origin/main
            docker compose up -d --build
